profile: '{cipher}AQBrL8pil2z7PszRKDxun/+5IUT+x4icgdnMxUjliw9SKFeLjSgE7FQD+IpWT9vpK1xLjwcPQGi59maVnaWoyyGgXBEPtEB02vMGf3vAp5Kjg7AVqB8I0YhfiznQGdGjxySMIWyvCy06Cvw8oB2VGW8f0Ex1507hsGgWqIRN9/wLmXPO8LuzegNvNk0xFFyRgLzAmRAvUfP2FB3q7r16r9BejsdOMoh9QBMFwztfC89y0FwMfYA7daWzRdBaOrNfI6+Olk6NTeycJVQuoDOEnoitNsr9inKojWtQMkY/B9sMmPC6IC5ZwGM21R8aH1yXqZU89UChuPPyDedjzs8zl24bMv35g2FzDhk+NoRE4xgvpp7+1GMqCnNTuikqSdScGJc='
spring:
 application:
  name:
   production-server
